/**
 * Explanation Prompt Builder
 *
 * Builds the constrained GPT prompt for explanation generation.
 * The prompt embeds the ranked offer's machine reasons, tradeoffs,
 * and score summary with strict instructions to prevent GPT from
 * recalculating, re-ranking, or inventing reasons.
 */

import type { RankedOffer, SearchContext, JourneyType } from '../types';

/**
 * Build the GPT explanation prompt for a ranked offer.
 *
 * @param rankedOffer - The ranked offer to explain
 * @param searchContext - The search context
 * @param journeyType - domestic or international
 * @returns The complete prompt string to send to GPT
 */
export function buildExplanationPrompt(
  rankedOffer: RankedOffer,
  searchContext: SearchContext,
  journeyType: JourneyType,
): string {
  const systemPrompt = `You are FareMind's flight recommendation explanation assistant.

You are given a deterministic ranking result generated by FareMind's rule-based ranking engine.

Your job is only to explain the ranking in clear, simple, human-friendly language.

Do not change the ranking.
Do not recalculate scores.
Do not invent new reasons.
Do not mention anything that is not present in the provided JSON.
Do not claim that this is the cheapest unless the JSON explicitly says so.
Do not claim baggage, refundability, or comfort benefits unless provided in the JSON.
Do not mention internal model names.

Write a concise explanation for the traveler.

Output format:
1. One short headline.
2. 3 to 5 bullet points explaining why FareMind recommends this option.
3. One tradeoff sentence if tradeoffs are provided.
4. Keep the tone helpful, confident, and simple.`;

  const rankingData = {
    offerId: rankedOffer.offerId,
    rank: rankedOffer.rank,
    airline: rankedOffer.airline,
    provider: rankedOffer.provider,
    finalScore: rankedOffer.finalScore,
    confidence: rankedOffer.confidence,
    machineReasons: rankedOffer.machineReasons,
    tradeoffs: rankedOffer.tradeoffs,
    appliedRules: rankedOffer.appliedRules.map(r => ({
      rule: r.ruleId,
      reason: r.reason,
    })),
    route: `${searchContext.origin} → ${searchContext.destination}`,
    journeyType,
    cabin: searchContext.cabin,
  };

  const userPrompt = `Here is the ranking result JSON for the #${rankedOffer.rank} ranked flight:

${JSON.stringify(rankingData, null, 2)}

Please generate a concise explanation for the traveler.`;

  return JSON.stringify({
    systemPrompt,
    userPrompt,
    model: 'gpt-4.1-mini',
    maxTokens: 300,
    temperature: 0.3,
  });
}

/**
 * Build a structured prompt object (for direct API use).
 */
export function buildExplanationMessages(
  rankedOffer: RankedOffer,
  searchContext: SearchContext,
  journeyType: JourneyType,
): { system: string; user: string } {
  const parsedPrompt = JSON.parse(
    buildExplanationPrompt(rankedOffer, searchContext, journeyType)
  );
  return {
    system: parsedPrompt.systemPrompt,
    user: parsedPrompt.userPrompt,
  };
}
